spring:
  application:
    name: movie-review-system
  datasource:
    url: jdbc:mysql://localhost:3306/movie_review_system
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update # Options: none, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081